sites = ['https://www.google.com',
         'https://www.youtube.com',
         'https://www.facebook.com/',
         'https://www.twitter.com',
         'https://www.amazon.com/',
         'https://www.instagram.com/',
         'https://www.yandex.ru',
         'https://www.weather.com/',
         'https://docs.python.org',
         'https://habr.com',
         'https://github.com',
         'https://stackoverflow.com',
         'https://online.mfa.gov.ua',
         'https://yammyk-django-heroku.herokuapp.com',
         'https://jinja.palletsprojects.com']
